@startmindmap
*[#ff9e9e] Гитара
**[#lightgreen] Найти библиотеку звуков гитары (струны от 0 до 12 лада)
***[#lightgreen] Обычный звук
*** Тихий звук (от большого пальца, например)
*** Громкий звук (акцентированный удар)
*** Заглушенная струна (X)
**[#ff9e9e] Разметка
*** по нотам
***[#ff9e9e] буквенной записью
*** кружочки на грифе


*[#ff9e9e] Аккорды
**[#yellow] Библиотека стандартных аккордов
** Изображение кружочками на ладах
** Возможность добавлять свои аккорды

*[#ff9e9e] Бой
**[#ff9e9e] Библиотека стандартных схем
** Возможность добавлять свои схемы
*** Возможность играть схемы пальцем и позже редактировать их
**[#ff9e9e] Удары
***[#ff9e9e] Вниз/вверх
*** Акцентированный вниз/вверх
*** Короткий вниз/вверх (басы/нижние струны)
*** Хлопок по всем струнам (XXXXXX)
**** Жмяк ногтями по струнам?

*[#ff9e9e] Перебор
**[#ff9e9e] Библиотека стандартных переборов
** Возможность добавлять свои переборы

* Скорость игры
** BPM
** Скорость проведения по струнам (бой)

* Импорт/Экспорт
** набор боев
** Аккорды
** Переборы
** Проекты (мелодии)

* Кроссплатформенность?
**[#ff9e9e] Мобильное приложение
**[#yellow] Сайт

* Хранение информации
**[#ff9e9e] Не хочу заморачиваться насчет безопасности\nРазмещения на серверах и т.д\nПроще дать возможность быстрого адекватного экспорта/импорта
** Сохранение N последних действий пользователя
** Автосохранение раз в t времени

* Хоткеи (много разных)

@endmindmap


