@startmindmap
*[#lightgreen] Гитара
**[#lightgreen] Найти библиотеку звуков гитары (струны от 0 до 15+ лада)
***[#lightgreen] Обычный звук
*** Тихий звук (от большого пальца, например)
*** Громкий звук (акцентированный удар)
*** Заглушенная струна (X)
**[#lightgreen] Разметка
*** по нотам
***[#lightgreen] буквенной записью
*** кружочки на грифе


*[#lightgreen] Аккорды
**[#lightgreen] Библиотека стандартных аккордов
** Изображение кружочками на ладах
** Возможность добавлять свои аккорды

*[#lightgreen] Бой
**[#lightgreen] Библиотека стандартных схем
** Возможность добавлять свои схемы
*** Возможность играть схемы пальцем и позже редактировать их
**[#lightgreen] Удары
***[#lightgreen] Вниз/вверх
*** Акцентированный вниз/вверх
*** Короткий вниз/вверх (басы/нижние струны)
*** Хлопок по всем струнам (XXXXXX)
**** Жмяк ногтями по струнам?

*[#lightgreen] Перебор
**[#lightgreen] Библиотека стандартных переборов
** Возможность добавлять свои переборы

* Скорость игры
** BPM
** Скорость проведения по струнам (бой)

* Импорт/Экспорт
** набор боев
** Аккорды
** Переборы
** Проекты (мелодии)

* Кроссплатформенность?
**[#lightyellow] Мобильное приложение
** Компудактерное приложение?
**[#lightgreen] Сайт

* Хранение информации
**[#lightgreen] Не хочу заморачиваться насчет безопасности\nРазмещения на серверах и т.д\nПроще дать возможность быстрого адекватного экспорта/импорта
** Сохранение N последних действий пользователя
** Автосохранение раз в t времени

@endmindmap


